import mongoose from 'mongoose';
import { ENV } from '../config/env.js';
import { Template } from '../models/Template.js';

const seedTemplates = [
  {
    title: 'মহান বিজয় দিবস - জাতীয় স্মৃতিসৌধ থিম',
    slug: 'victory-day-memorial',
    occasionType: 'victory_day',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#043927',
      bgGradient: 'linear-gradient(180deg, #043927 0%, #021f15 100%)',
      bannerColor: '#c9182b',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'প্রধান নেতা (কেন্দ্রীয়)',
          x: 485,
          y: 60,
          width: 230,
          height: 300,
          shape: 'oval',
          borderWidth: 6,
          borderColor: '#f59e0b',
        },
        {
          id: 'leader_2',
          label: 'শীর্ষ নেতা (বাম)',
          x: 230,
          y: 100,
          width: 180,
          height: 240,
          shape: 'oval',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
        {
          id: 'leader_3',
          label: 'শীর্ষ নেতা (ডান)',
          x: 790,
          y: 100,
          width: 180,
          height: 240,
          shape: 'oval',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
        {
          id: 'requester',
          label: 'আপনার ছবি (প্রচারে)',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
      ],
      textSlots: [
        {
          id: 'party',
          label: 'দল / সংগঠনের নাম',
          x: 600,
          y: 430,
          fontSize: 28,
          fontWeight: 700,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
        {
          id: 'headline',
          label: 'মূল শিরোনাম',
          x: 600,
          y: 530,
          fontSize: 84,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'স্লোগান / বাণী',
          x: 600,
          y: 680,
          width: 960,
          fontSize: 32,
          fontWeight: 600,
          color: '#fef08a',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
        {
          id: 'requester_name',
          label: 'আপনার নাম',
          x: 100,
          y: 1350,
          fontSize: 54,
          fontWeight: 800,
          color: '#ffffff',
          align: 'left',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'designation',
          label: 'পদবি ও এলাকা',
          x: 100,
          y: 1420,
          fontSize: 28,
          fontWeight: 600,
          color: '#fef08a',
          align: 'left',
          fontFamily: 'Hind Siliguri',
        },
        {
          id: 'credit_line',
          label: 'প্রচারে লাইন',
          x: 600,
          y: 1570,
          fontSize: 16,
          fontWeight: 400,
          color: '#94a3b8',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'গভীর শোক ও বিনম্র শ্রদ্ধাঞ্জলি',
    slug: 'memorial-tribute',
    occasionType: 'mourning',
    partyMotif: 'neutral',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#18181b',
      bgGradient: 'linear-gradient(180deg, #18181b 0%, #09090b 100%)',
      bannerColor: '#3f3f46',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'স্মরণীয় নেতার প্রতিকৃতি',
          x: 475,
          y: 80,
          width: 250,
          height: 320,
          shape: 'oval',
          borderWidth: 6,
          borderColor: '#e4e4e7',
        },
        {
          id: 'requester',
          label: 'শোক সন্তপ্ত (আপনার ছবি)',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 3,
          borderColor: '#a1a1aa',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শোকবাণী',
          x: 600,
          y: 520,
          fontSize: 78,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'শ্রদ্ধাঞ্জলি বাণী',
          x: 600,
          y: 670,
          width: 900,
          fontSize: 32,
          fontWeight: 500,
          color: '#d4d4d8',
          align: 'center',
          fontFamily: 'Tiro Bangla',
        },
        {
          id: 'requester_name',
          label: 'শোক প্রকাশকারী',
          x: 100,
          y: 1350,
          fontSize: 50,
          fontWeight: 800,
          color: '#ffffff',
          align: 'left',
          fontFamily: 'Anek Bangla',
        },
      ],
    },
  },
  {
    title: 'নির্বাচনী প্রচার ও বিজয়ের শুভেচ্ছা',
    slug: 'election-campaign-banner',
    occasionType: 'campaign',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#064e3b',
      bgGradient: 'linear-gradient(180deg, #064e3b 0%, #022c22 100%)',
      bannerColor: '#dc2626',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'দলীয় প্রধান',
          x: 350,
          y: 70,
          width: 210,
          height: 280,
          shape: 'oval',
          borderWidth: 5,
          borderColor: '#f59e0b',
        },
        {
          id: 'leader_2',
          label: 'সাধারণ সম্পাদক / শীর্ষ নেতা',
          x: 640,
          y: 70,
          width: 210,
          height: 280,
          shape: 'oval',
          borderWidth: 5,
          borderColor: '#f59e0b',
        },
        {
          id: 'requester',
          label: 'প্রার্থী / আপনার ছবি',
          x: 880,
          y: 1250,
          width: 240,
          height: 300,
          shape: 'rect',
          borderWidth: 5,
          borderColor: '#f59e0b',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'নির্বাচনী স্লোগান / আহ্বান',
          x: 600,
          y: 500,
          fontSize: 80,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'প্রতিশ্রুতি / আবেদন',
          x: 600,
          y: 650,
          width: 950,
          fontSize: 34,
          fontWeight: 600,
          color: '#fde047',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'আমেরিকান পপ-আর্ট "হোপ" শৈলী (Shepard Fairey Style)',
    slug: 'pop-art-hope-style',
    occasionType: 'international',
    partyMotif: 'international',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#003049',
      bgGradient: 'linear-gradient(180deg, #669bbc 0%, #003049 55%, #780001 100%)',
      bannerColor: '#c1121f',
      footerColor: '#003049',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'প্রার্থী / নেতার প্রতিকৃতি (সেন্ট্রাল)',
          x: 350,
          y: 120,
          width: 500,
          height: 600,
          shape: 'rect',
          borderWidth: 8,
          borderColor: '#fdf0d5',
        },
        {
          id: 'requester',
          label: 'প্রচারের প্রতিকৃতি',
          x: 900,
          y: 1280,
          width: 210,
          height: 260,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#fdf0d5',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শব্দ বা প্রত্যয় (HOPE / প্রগতি)',
          x: 600,
          y: 820,
          fontSize: 88,
          fontWeight: 800,
          color: '#fdf0d5',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'ক্যাম্পেইন বার্তা',
          x: 600,
          y: 930,
          width: 900,
          fontSize: 32,
          fontWeight: 600,
          color: '#669bbc',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'কনস্ট্রাক্টিভিস্ট অ্যাজিটপ্রপ শৈলী (Soviet Avant-Garde)',
    slug: 'constructivist-agitprop-style',
    occasionType: 'international',
    partyMotif: 'international',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#171717',
      bgGradient: 'linear-gradient(135deg, #991b1b 0%, #171717 60%, #0a0a0a 100%)',
      bannerColor: '#dc2626',
      footerColor: '#0a0a0a',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'কেন্দ্রীয় নেতা (ডায়াগনাল)',
          x: 450,
          y: 90,
          width: 300,
          height: 380,
          shape: 'rect',
          borderWidth: 6,
          borderColor: '#dc2626',
        },
        {
          id: 'requester',
          label: 'আপনার ছবি',
          x: 880,
          y: 1250,
          width: 230,
          height: 280,
          shape: 'rect',
          borderWidth: 5,
          borderColor: '#ffffff',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'বলিষ্ঠ ডাক / স্লোগান',
          x: 600,
          y: 560,
          fontSize: 86,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'জনগণের জাগরণ',
          x: 600,
          y: 690,
          width: 950,
          fontSize: 34,
          fontWeight: 700,
          color: '#f87171',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'সুইস মিনিম্যালিস্ট শৈলী (Swiss International Grid)',
    slug: 'swiss-minimalist-grid',
    occasionType: 'international',
    partyMotif: 'civic',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#f8fafc',
      bgGradient: 'linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)',
      bannerColor: '#0284c7',
      footerColor: '#0f172a',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'নাগরিক প্রতিনিধি (গ্রিড স্লট)',
          x: 460,
          y: 100,
          width: 280,
          height: 360,
          shape: 'rect',
          borderWidth: 3,
          borderColor: '#0f172a',
        },
        {
          id: 'requester',
          label: 'আপনার প্রতিকৃতি',
          x: 880,
          y: 1260,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 2,
          borderColor: '#0284c7',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'নাগরিক অধিকার ও উন্নয়ন',
          x: 600,
          y: 530,
          fontSize: 76,
          fontWeight: 800,
          color: '#0f172a',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
        {
          id: 'slogan',
          label: 'সুশাসন ও স্বচ্ছতা',
          x: 600,
          y: 660,
          width: 900,
          fontSize: 30,
          fontWeight: 500,
          color: '#475569',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'ল্যাটিন সলিডারিটি মুরাল শৈলী (Grassroots & Muralist)',
    slug: 'latin-solidarity-mural',
    occasionType: 'international',
    partyMotif: 'progressive',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#7c2d12',
      bgGradient: 'radial-gradient(circle at 50% 25%, #d97706 0%, #7c2d12 70%, #451a03 100%)',
      bannerColor: '#ea580c',
      footerColor: '#291004',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'জনগণের নেতা (সূর্যবলয় ফ্রেম)',
          x: 470,
          y: 90,
          width: 260,
          height: 340,
          shape: 'oval',
          borderWidth: 6,
          borderColor: '#fef08a',
        },
        {
          id: 'requester',
          label: 'প্রার্থীর ছবি',
          x: 880,
          y: 1260,
          width: 230,
          height: 280,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#fef08a',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'গণঐক্য ও বিপ্লব',
          x: 600,
          y: 520,
          fontSize: 82,
          fontWeight: 800,
          color: '#fef08a',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'মেহনতি মানুষের বিজয়',
          x: 600,
          y: 660,
          width: 950,
          fontSize: 32,
          fontWeight: 600,
          color: '#fed7aa',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'অমর একুশে ফেব্রুয়ারি - শহীদ মিনার ও শান্তির পায়রা',
    slug: 'shaheed-minar-language-day',
    occasionType: 'mourning',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#f8fafc',
      bgGradient: 'linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%)',
      bannerColor: '#991b1b',
      footerColor: '#0f172a',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'শ্রদ্ধাঞ্জলি ব্যক্তিত্ব',
          x: 485,
          y: 60,
          width: 230,
          height: 290,
          shape: 'oval',
          borderWidth: 5,
          borderColor: '#991b1b',
        },
        {
          id: 'requester',
          label: 'আপনার ছবি',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#991b1b',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শিরোনাম',
          x: 600,
          y: 530,
          fontSize: 82,
          fontWeight: 800,
          color: '#0f172a',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'শ্রদ্ধাঞ্জলি বাণী',
          x: 600,
          y: 680,
          width: 960,
          fontSize: 32,
          fontWeight: 600,
          color: '#991b1b',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: '১৬ই ডিসেম্বর - দৃপ্ত বজ্রমুষ্টি ও মুক্তির সংগ্রাম',
    slug: 'victory-day-fist-of-freedom',
    occasionType: 'victory_day',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#022c22',
      bgGradient: 'linear-gradient(180deg, #022c22 0%, #064e3b 100%)',
      bannerColor: '#dc2626',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'জাতীয় বীর / নেতা',
          x: 485,
          y: 60,
          width: 230,
          height: 300,
          shape: 'shield',
          borderWidth: 6,
          borderColor: '#f59e0b',
        },
        {
          id: 'requester',
          label: 'আপনার ছবি',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শিরোনাম',
          x: 600,
          y: 530,
          fontSize: 84,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'স্লোগান',
          x: 600,
          y: 680,
          width: 960,
          fontSize: 32,
          fontWeight: 600,
          color: '#fef08a',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'গৌরবময় প্রতিষ্ঠা বার্ষিকী ও দলীয় সম্মেলন',
    slug: 'party-anniversary-celebration',
    occasionType: 'anniversary',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#064e3b',
      bgGradient: 'linear-gradient(180deg, #064e3b 0%, #022c22 100%)',
      bannerColor: '#f59e0b',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'leader_1',
          label: 'প্রতিষ্ঠাতা / চেয়ারম্যান',
          x: 485,
          y: 60,
          width: 230,
          height: 300,
          shape: 'arch',
          borderWidth: 6,
          borderColor: '#f59e0b',
        },
        {
          id: 'requester',
          label: 'আপনার ছবি',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'rect',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শিরোনাম',
          x: 600,
          y: 530,
          fontSize: 84,
          fontWeight: 800,
          color: '#fef08a',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'সম্মেলন বার্তা',
          x: 600,
          y: 680,
          width: 960,
          fontSize: 32,
          fontWeight: 600,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
  {
    title: 'তারুণ্যের গণজোয়ার ও নির্বাচনী মার্কা',
    slug: 'youth-rally-campaign',
    occasionType: 'campaign',
    partyMotif: 'general_bangladesh',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop',
    isActive: true,
    layoutConfig: {
      dimensions: { width: 1200, height: 1600 },
      bgColor: '#065f46',
      bgGradient: 'linear-gradient(180deg, #065f46 0%, #043927 100%)',
      bannerColor: '#dc2626',
      footerColor: '#000000',
      photoSlots: [
        {
          id: 'requester',
          label: 'প্রার্থীর ছবি (হিরো)',
          x: 900,
          y: 1280,
          width: 220,
          height: 270,
          shape: 'cutout',
          borderWidth: 4,
          borderColor: '#f59e0b',
        },
      ],
      textSlots: [
        {
          id: 'headline',
          label: 'মূল শিরোনাম',
          x: 600,
          y: 530,
          fontSize: 82,
          fontWeight: 800,
          color: '#ffffff',
          align: 'center',
          fontFamily: 'Anek Bangla',
        },
        {
          id: 'slogan',
          label: 'নির্বাচনী স্লোগান',
          x: 600,
          y: 680,
          width: 960,
          fontSize: 32,
          fontWeight: 600,
          color: '#fef08a',
          align: 'center',
          fontFamily: 'Hind Siliguri',
        },
      ],
    },
  },
];

async function runSeed() {
  try {
    console.log('[Seed] Connecting to MongoDB:', ENV.MONGODB_URI);
    await mongoose.connect(ENV.MONGODB_URI);

    console.log('[Seed] Clearing existing templates...');
    await Template.deleteMany({});

    console.log('[Seed] Inserting authentic Bangladeshi political poster templates...');
    const created = await Template.insertMany(seedTemplates);
    console.log(`[Seed] Successfully seeded ${created.length} templates!`);

    await mongoose.disconnect();
    console.log('[Seed] Done.');
  } catch (error) {
    console.error('[Seed] Error during template seeding:', error);
    process.exit(1);
  }
}

runSeed();
